name: aad
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - matplotlib
  - numpy
  - opencv
  - jupyterlab
  - ipywidgets
  - albumentations==0.5.1
  - pytorch==1.7.0
  - torchvision==0.8.1
  - pip
  - pip:
    - segmentation-models-pytorch==0.1.2
    - pyclothoids
    - pygame